# Generated by Django 6.0.6 on 2026-06-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('organism', models.CharField(choices=[('pf', 'Plasmodium falciparum'), ('pv', 'Plasmodium vivax'), ('ag', 'Anopheles gambiae'), ('other', 'Other')], default='other', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('fastq_r1', 'FASTQ R1'), ('fastq_r2', 'FASTQ R2'), ('fastq_single', 'FASTQ single-end'), ('bam', 'BAM'), ('vcf', 'VCF'), ('other', 'Other')], max_length=20)),
                ('file_size_bytes', models.BigIntegerField()),
                ('md5_checksum', models.CharField(blank=True, max_length=32)),
                ('is_validated', models.BooleanField(default=False)),
                ('upload_status', models.CharField(choices=[('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(help_text="The lab's identifier for this sample.", max_length=100)),
                ('external_id', models.CharField(blank=True, help_text='External identifier, e.g. a MalariaGEN ID.', max_length=100)),
                ('species', models.CharField(choices=[('pf', 'Plasmodium falciparum'), ('pv', 'Plasmodium vivax'), ('ag', 'Anopheles gambiae'), ('other', 'Other')], default='other', max_length=10)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('collection_location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SequencingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=100, unique=True)),
                ('instrument', models.CharField(choices=[('illumina_miseq', 'Illumina MiSeq'), ('illumina_hiseq', 'Illumina HiSeq'), ('illumina_nextseq', 'Illumina NextSeq'), ('illumina_novaseq', 'Illumina NovaSeq'), ('ion_torrent', 'Ion Torrent'), ('nanopore', 'Oxford Nanopore'), ('other', 'Other')], default='other', max_length=20)),
                ('chip_id', models.CharField(blank=True, help_text='Flowcell / chip barcode.', max_length=100)),
                ('run_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
