# Generated by Django 6.0.6 on 2026-06-24 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='samples.project'),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_files', to='samples.sample'),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequencing_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='sequencing_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_files', to='samples.sequencingrun'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='unique_project_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['sample_id'], name='samples_sam_sample__75a926_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['species'], name='samples_sam_species_aebb5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.UniqueConstraint(fields=('sample_id', 'project'), name='unique_sample_id_per_project'),
        ),
        migrations.AddIndex(
            model_name='rawfile',
            index=models.Index(fields=['upload_status'], name='samples_raw_upload__afec31_idx'),
        ),
    ]
