# Generated by Django 6.0.6 on 2026-06-24 09:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('workflow_type', models.CharField(choices=[('single_qc', 'Single sample — QC'), ('single_full', 'Single sample — full (QC + align + call + annotate)'), ('pop_joint', 'Population — joint calling'), ('pop_structure', 'Population — structure'), ('pop_phylo', 'Population — phylogenetics'), ('pop_selection', 'Population — selection'), ('pop_full', 'Population — full')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('parameters', models.JSONField(default=dict)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('nextflow_run_name', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('progress_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('output_dir', models.CharField(blank=True, max_length=1000)),
                ('execution_log', models.TextField(blank=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisJobSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_samples', to='workflows.analysisjob')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_samples', to='samples.sample')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='samples',
            field=models.ManyToManyField(related_name='analysis_jobs', through='workflows.AnalysisJobSample', to='samples.sample'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('qc_report', 'QC report'), ('alignment_stats', 'Alignment stats'), ('variant_calls', 'Variant calls'), ('annotated_variants', 'Annotated variants'), ('fws', 'Fws'), ('ibd_matrix', 'IBD matrix'), ('admixture', 'Admixture'), ('phylogenetic_tree', 'Phylogenetic tree'), ('diversity_stats', 'Diversity stats'), ('selection_scan', 'Selection scan'), ('full_report', 'Full report'), ('other', 'Other')], max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('summary_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='workflows.analysisjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='analysisjobsample',
            constraint=models.UniqueConstraint(fields=('job', 'sample'), name='unique_job_sample'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status'], name='workflows_a_status_7516d4_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['workflow_type'], name='workflows_a_workflo_56ce84_idx'),
        ),
    ]
