"""initial schema

Revision ID: 120990da7cd5
Revises: 
Create Date: 2026-07-05 05:41:51.682366
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '120990da7cd5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keycloak_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_keycloak_id'), 'users', ['keycloak_id'], unique=True)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workflow_type', sa.Enum('SINGLE_SAMPLE_QC', 'SINGLE_SAMPLE_FULL', 'POPULATION_JOINT_CALLING', 'POPULATION_STRUCTURE', 'POPULATION_PHYLOGENETICS', 'POPULATION_SELECTION', 'POPULATION_FULL', name='workflowtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=False),
    sa.Column('nextflow_run_name', sa.String(length=255), nullable=False),
    sa.Column('submitted_by_id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('output_dir', sa.String(length=1000), nullable=False),
    sa.Column('execution_log', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status', 'analysis_jobs', ['status'], unique=False)
    op.create_index('ix_jobs_submitted_by', 'analysis_jobs', ['submitted_by_id'], unique=False)
    op.create_index('ix_jobs_workflow_type', 'analysis_jobs', ['workflow_type'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('organism', sa.Enum('PF', 'PV', 'AG', 'OTHER', name='organism'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'created_by_id', name='uq_project_name_user')
    )
    op.create_table('sequencing_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('instrument', sa.Enum('ILLUMINA_MISEQ', 'ILLUMINA_HISEQ', 'ILLUMINA_NEXTSEQ', 'ILLUMINA_NOVASEQ', 'ION_TORRENT', 'NANOPORE', 'OTHER', name='instrument'), nullable=False),
    sa.Column('chip_id', sa.String(length=100), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=False),
    sa.Column('storage_quota_gb', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.Enum('SINGLE_SAMPLE', 'POPULATION', 'CUSTOM', name='reporttype'), nullable=False),
    sa.Column('minio_object_key', sa.String(length=1000), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('generated_by_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('result_type', sa.Enum('QC_REPORT', 'ALIGNMENT_STATS', 'VARIANT_CALLS', 'ANNOTATED_VARIANTS', 'FWS', 'IBD_MATRIX', 'ADMIXTURE', 'PHYLOGENETIC_TREE', 'DIVERSITY_STATS', 'SELECTION_SCAN', 'FULL_REPORT', 'OTHER', name='resulttype'), nullable=False),
    sa.Column('minio_object_key', sa.String(length=1000), nullable=False),
    sa.Column('summary_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('species', sa.Enum('PF', 'PV', 'AG', 'OTHER', name='organism'), nullable=False),
    sa.Column('collection_date', sa.Date(), nullable=True),
    sa.Column('collection_location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'project_id', name='uq_sample_id_project')
    )
    op.create_index('ix_samples_project_id', 'samples', ['project_id'], unique=False)
    op.create_index('ix_samples_sample_id', 'samples', ['sample_id'], unique=False)
    op.create_table('analysis_job_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('sequencing_run_id', sa.UUID(), nullable=True),
    sa.Column('minio_object_key', sa.String(length=1000), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.Enum('FASTQ_R1', 'FASTQ_R2', 'FASTQ_SINGLE', 'BAM', 'VCF', 'OTHER', name='filetype'), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('md5_checksum', sa.String(length=32), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('upload_status', sa.Enum('UPLOADING', 'COMPLETED', 'FAILED', name='uploadstatus'), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequencing_run_id'], ['sequencing_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_files_sample_id', 'raw_files', ['sample_id'], unique=False)
    op.create_index(op.f('ix_raw_files_upload_status'), 'raw_files', ['upload_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_files_upload_status'), table_name='raw_files')
    op.drop_index('ix_raw_files_sample_id', table_name='raw_files')
    op.drop_table('raw_files')
    op.drop_table('analysis_job_samples')
    op.drop_index('ix_samples_sample_id', table_name='samples')
    op.drop_index('ix_samples_project_id', table_name='samples')
    op.drop_table('samples')
    op.drop_table('results')
    op.drop_table('reports')
    op.drop_table('user_profiles')
    op.drop_table('sequencing_runs')
    op.drop_table('projects')
    op.drop_index('ix_jobs_workflow_type', table_name='analysis_jobs')
    op.drop_index('ix_jobs_submitted_by', table_name='analysis_jobs')
    op.drop_index('ix_jobs_status', table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_users_keycloak_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
